# Generated by Django 3.1.5 on 2021-01-25 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('CLI', 'Cliente')], default='CLI', max_length=10)),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12)),
                ('precio', models.IntegerField()),
                ('informacion', models.CharField(max_length=25)),
                ('fecha_adquision', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminProductosApp.usuarios')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
