# Generated by Django 3.1.5 on 2021-01-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProductosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='informacion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='0'),
        ),
    ]
